name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: "Release"
    env:
      NODE_VERSION: '12.x'                # set this to the node version to use

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Run Unit Tests
      run: |
        npm install
        npm run test

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    # Add files to release
    - name: Upload estate aggregator projection file to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/EventStoreProjections/EventStoreProjections/src/continuous/EstateAggregator.js
        asset_name: EstateAggregator.js
        tag: ${{ github.ref }}
        overwrite: true
        body: "Estate Aggregator Projection"

    - name: Upload file processor subscription stream builder projection file to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/EventStoreProjections/EventStoreProjections/src/continuous/FileProcessorSubscriptionStreamBuilder.js
        asset_name: FileProcessorSubscriptionStreamBuilder.js
        tag: ${{ github.ref }}
        overwrite: true
        body: "File Processor Subscription Stream Builder Projection" 

    - name: Upload merchant aggregator projection file to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/EventStoreProjections/EventStoreProjections/src/continuous/MerchantAggregator.js
        asset_name: MerchantAggregator.js
        tag: ${{ github.ref }}
        overwrite: true
        body: "Merchant Aggregator Projection"

    - name: Upload merchant balance calculator projection file to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/EventStoreProjections/EventStoreProjections/src/continuous/MerchantBalanceCalculator.js
        asset_name: MerchantBalanceCalculator.js
        tag: ${{ github.ref }}
        overwrite: true
        body: "Merchant Balance Calculator Projection"        

    - name: Upload transaction enricher projection file to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/EventStoreProjections/EventStoreProjections/src/continuous/TransactionEnricher.js
        asset_name: TransactionEnricher.js
        tag: ${{ github.ref }}
        overwrite: true
        body: "Transaction Enricher Projection"

    - name: Upload transaction processor subscription stream builder projection file to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/EventStoreProjections/EventStoreProjections/src/continuous/TransactionProcessorSubscriptionStreamBuilder.js
        asset_name: TransactionProcessorSubscriptionStreamBuilder.js
        tag: ${{ github.ref }}
        overwrite: true
        body: "Transaction Processor Subscription Stream Builder Projection" 

    - name: Upload callback handler subscription stream builder projection file to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/work/EventStoreProjections/EventStoreProjections/src/continuous/CallbackHandlerEnricher.js
        asset_name: CallbackHandlerEnricher.js
        tag: ${{ github.ref }}
        overwrite: true
        body: "Callback Handler Subscription Stream Builder Projection" 
