name: Nightly Build

on:
  schedule:
  - cron: "45 23 * * *"
  repository_dispatch:

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  nightlybuild:
    name: Nightly Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Run Unit Tests
      run: |
        npm install
        npm run test
